version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map lokal port 8080 til containerens 8080
    environment:
      - DEPLOYED=true
      - DB_NAME=animal_care
      - CONNECTION_STR=jdbc:postgresql://db:5432/animal_care
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db # Gør appen afhængig af databasen

  db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: animal_care
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Map lokal port 5432 til containerens 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
